export const VAULT_TERMINOLOGY = {
  worldbuilding: {
    vault: 'World',
    note: 'Article',
    notes: 'Articles',
    folder: 'Category',
    folders: 'Categories',
    character: 'Entity',
    characters: 'Entities',
    charSpecies: 'Species / Origin',
    charRole: 'Role / Archetype',
    charTypePc: 'Protagonist',
    charTypeNpc: 'Supporting Entity',
    charTypeAntagonist: 'Antagonist',
    charTypeBackground: 'Background Entity',
    session: 'Chronicle',
    sessions: 'Chronicles',
    sessionNotes: 'Chronicle Notes',
    milestone: 'Milestone',
    participants: 'Participants',
    discoveries: 'Discoveries',
    map: 'Map',
    maps: 'Maps',
    relationship: 'Relationship',
    graph: 'Relationship Graph',
    aiSummary: 'AI Summary',
  },

  tabletop: {
    vault: 'Campaign',
    note: 'Lore Entry',
    notes: 'Lore Entries',
    folder: 'Category',
    folders: 'Categories',
    character: 'Character',
    characters: 'Characters',
    charSpecies: 'Race',
    charRole: 'Class',
    charTypePc: 'Player Character',
    charTypeNpc: 'NPC',
    charTypeAntagonist: 'Villain',
    charTypeBackground: 'Background Figure',
    session: 'Session',
    sessions: 'Sessions',
    sessionNotes: 'Session Notes',
    milestone: 'XP / Milestone',
    participants: 'Party Members',
    discoveries: 'Loot & Discoveries',
    map: 'Map',
    maps: 'Maps',
    relationship: 'Relationship',
    graph: 'Relationship Graph',
    aiSummary: 'AI Recap',
  },

  video_game: {
    vault: 'Game World',
    note: 'Codex Entry',
    notes: 'Codex Entries',
    folder: 'Category',
    folders: 'Categories',
    character: 'Character',
    characters: 'Characters',
    charSpecies: 'Species',
    charRole: 'Build',
    charTypePc: 'Player Character',
    charTypeNpc: 'NPC',
    charTypeAntagonist: 'Boss / Enemy',
    charTypeBackground: 'Background NPC',
    session: 'Playthrough',
    sessions: 'Playthroughs',
    sessionNotes: 'Playthrough Notes',
    milestone: 'Achievement Points',
    participants: 'Player Characters',
    discoveries: 'Drops & Rewards',
    map: 'Map',
    maps: 'Maps',
    relationship: 'Relationship',
    graph: 'Relationship Graph',
    aiSummary: 'AI Summary',
  },

  novel: {
    vault: 'Story World',
    note: 'Story Note',
    notes: 'Story Notes',
    folder: 'Section',
    folders: 'Sections',
    character: 'Character',
    characters: 'Characters',
    charSpecies: 'Species / Origin',
    charRole: 'Role',
    charTypePc: 'Protagonist',
    charTypeNpc: 'Supporting Character',
    charTypeAntagonist: 'Antagonist',
    charTypeBackground: 'Background Character',
    session: 'Chapter',
    sessions: 'Chapters',
    sessionNotes: 'Chapter Notes',
    milestone: 'Story Beat',
    participants: 'Characters',
    discoveries: 'Plot Reveals',
    map: 'Location Map',
    maps: 'Location Maps',
    relationship: 'Relationship',
    graph: 'Story Web',
    aiSummary: 'Chapter Summary',
  },

  film: {
    vault: 'Production',
    note: 'Script Note',
    notes: 'Script Notes',
    folder: 'Act',
    folders: 'Acts',
    character: 'Character',
    characters: 'Characters',
    charSpecies: 'Background',
    charRole: 'Role',
    charTypePc: 'Lead',
    charTypeNpc: 'Supporting',
    charTypeAntagonist: 'Antagonist',
    charTypeBackground: 'Background',
    session: 'Episode',
    sessions: 'Episodes',
    sessionNotes: 'Episode Notes',
    milestone: 'Scene Beat',
    participants: 'Cast',
    discoveries: 'Plot Points',
    map: 'Location',
    maps: 'Locations',
    relationship: 'Relationship',
    graph: 'Story Web',
    aiSummary: 'Episode Summary',
  },
};

// custom falls back to worldbuilding — user-defined labels are a future feature
VAULT_TERMINOLOGY.custom = VAULT_TERMINOLOGY.worldbuilding;

export const DEFAULT_TERMINOLOGY = VAULT_TERMINOLOGY.worldbuilding;
